# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


description: >-
I am a PhD student in the Computer Science Department at the University of Maryland, College Park. 
I am working with [Prof. Yiannis Aloimonos](https://robotics.umd.edu/clark/faculty/350/Yiannis-Aloimonos) and [Cornelia Fermüller](http://users.umiacs.umd.edu/~fer/) at [Perception and Robotics Group](https://prg.cs.umd.edu/). I also work closely with [Prof. Christopher Metzler](http://www.cs.umd.edu/~metzler/). 
During my master's study I worked with [Prof. Pratap Tokekar](http://tokekar.com/) on using Reinforcement Learning in Multi-agent System research. <br>

My research interest lies at the intersection of computer vision, imaging, and robotics, focusing on generative models, 
neural representations for motion in videos, and 3D vision for robotics.

url: https://codingrex.github.io/
name: Jingxi Chen
baseurl: ""
google_scholar: jcfUmocAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
